### ISSUE TITLE
if size is more then 6 mb it is not working

### ISSUE THREAD

**Issue by hitubansal123** [mindblaze/streaming-s3#11]
Hello 

I have a file having size  more than 6 mb . 

//set options for the streaming module
    var options = {
        concurrentParts: 2,
        waitTime: 20000,
        retries: 2,
        maxPartSize: 10 * 1024 * 1024
    };
    //call stream function to upload the file to s3
    var uploader = new streamingS3(fileReadStream, config.aws.accessKey, config.aws.secretKey, awsHeader, options);
    //start uploading
    uploader.begin();// important if callback not provided.
    
    // handle these functions
    uploader.on('data', function (bytesRead) {
        console.log(bytesRead, ' bytes read.');
    });
    
    uploader.on('part', function (number) {
        console.log('Part ', number, ' uploaded.');
    });
    
    // All parts uploaded, but upload not yet acknowledged.
    uploader.on('uploaded', function (stats) {
        console.log('Upload stats: ', stats);
    });
    
    uploader.on('finished', function (response, stats) {
        console.log(response);
        logger.log('info', "UPLOAD ", response);
        cb(null, response);
    });
    
    uploader.on('error', function (err) {
        console.log('Upload error: ', err);
        logger.log('error', "UPLOAD Error: ", err);
        cb(err);
    });

whn i check on awa file size is 5 Mb. why it is not 6 mb. and file is not opening properly.

**Comment by talha-asad** [comment]
I am not sure how your code is structured. Can you please put it in one code block?

**Comment by hitubansal123** [comment]
I am closing this issue. it was a typo with me . 

Thanks
