### ISSUE TITLE
Piping the stream to a secondary

### ISSUE THREAD

**Issue by dainbrump** [mindblaze/streaming-s3#12]
I may be approaching a problem the wrong way. I have a collection of files on remote systems that I want uploaded to S3 via request. So far, so good. The module does this beautifully. Now I have the added requirement of when a file matches certain criteria, I need to upload it to S3 AND stream it to another location (example: a writeStream). I thought using pipes on the request might do it, but that doesn't seem to work. I'm still relatively new to Node so this may be a noob question.

**Comment by talha-asad** [comment]
This is pretty easy to do, paste some sample code an i'll help you get this done. This is exactly why i built this module anyway.
