### ISSUE TITLE
Signature Does Not Match

### ISSUE THREAD

**Issue by kburkettgeo** [mindblaze/streaming-s3#8]
I try this:

![image](https://cloud.githubusercontent.com/assets/3661273/6472466/9d722134-c1a7-11e4-9762-eb25b1f0863a.png)

and I get:

![image](https://cloud.githubusercontent.com/assets/3661273/6472506/ebdb5f02-c1a7-11e4-8710-5f4f33bdfaf8.png)

I have checked my S3 policy to verify that my user can access my s3 bucket.

Any ideas?

**Comment by talha-asad** [comment]
Thats an error originating from the underlying aws-sdk. You can probably try the things mentioned here https://forums.aws.amazon.com/thread.jspa?threadID=75517

**Comment by kburkettgeo** [comment]
i decided to rebuild by user access key, and that worked.  thanks!
